CREATE TABLE fitscribe_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  email_address TEXT NOT NULL
);

ALTER TABLE fitscribe_workouts
  ADD COLUMN
    author_id INTEGER REFERENCES fitscribe_users(id)
    ON DELETE SET NULL;