CREATE TYPE muscle_group AS ENUM (
  'Chest',
  'Back',
  'Shoulders',
  'Arms',
  'Quads',
  'Hamstrings',
  'Calves',
  'Abs'
);

CREATE TABLE fitscribe_exercises (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  liftName TEXT NOT NULL,
  muscle_group muscle_group NOT NULL
);