CREATE TABLE fitscribe_weeks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES fitscribe_users(id),
  sunday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  sunday_status BOOLEAN NOT NULL DEFAULT FALSE,
  monday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  monday_status BOOLEAN NOT NULL DEFAULT FALSE,
  tuesday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  tuesday_status BOOLEAN NOT NULL DEFAULT FALSE,
  wednesday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  wednesday_status BOOLEAN NOT NULL DEFAULT FALSE,
  thursday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  thursday_status BOOLEAN NOT NULL DEFAULT FALSE,
  friday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  friday_status BOOLEAN NOT NULL DEFAULT FALSE,
  saturday_workout INTEGER REFERENCES fitscribe_workouts(id) DEFAULT NULL,
  saturday_status BOOLEAN NOT NULL DEFAULT FALSE
);